// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Phoenix_Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void signUpValidEmail() {
        driver.get("http://localhost:4000/");
        driver.findElement(By.linkText("Create new account")).click();
        driver.findElement(By.id("user_first_name")).click();
        driver.findElement(By.id("user_first_name")).sendKeys("nusrat");
        driver.findElement(By.id("user_last_name")).click();
        driver.findElement(By.id("user_last_name")).sendKeys("sharmin");
        driver.findElement(By.id("user_email")).click();
        driver.findElement(By.id("user_email")).sendKeys("bsse1441@iit.du.ac.bd");
        driver.findElement(By.id("user_password")).click();
        driver.findElement(By.id("user_password")).sendKeys("123456");
        driver.findElement(By.id("user_password_confirmation")).click();
        driver.findElement(By.id("user_password_confirmation")).sendKeys("123456");
        driver.findElement(By.cssSelector("button")).click();
    }

    @Test
    public void loginValidInput() {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(758, 700));
        driver.findElement(By.id("user_email")).click();
        driver.findElement(By.id("user_email")).click();
        {
            WebElement element = driver.findElement(By.id("user_email"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("user_email")).click();
        driver.findElement(By.id("user_email")).sendKeys("bsse1441@iit.du.ac.bd");
        driver.findElement(By.id("user_password")).click();
        driver.findElement(By.id("user_password")).click();
        driver.findElement(By.id("user_password")).sendKeys("123456");
        driver.findElement(By.id("user_password")).sendKeys(Keys.ENTER);
    }

    @Test
    public void loginIncorrectEmail() {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(760, 705));
        {
            WebElement element = driver.findElement(By.id("user_email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.id("user_email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.id("user_email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.id("user_email")).click();
        driver.findElement(By.id("user_email")).sendKeys("abc@gmail.com");
        driver.findElement(By.cssSelector("button")).click();
    }

    @Test
    public void loginInvalidPassword() {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(760, 705));
        {
            WebElement element = driver.findElement(By.id("user_email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.id("user_email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.id("user_email"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.id("user_email")).click();
        driver.findElement(By.id("user_email")).sendKeys("tazkiah@gmail.com");
        driver.findElement(By.id("user_password")).click();
        driver.findElement(By.id("user_password")).sendKeys("faoijoaq");
        driver.findElement(By.cssSelector("button")).click();
    }

    @Test
    public void createBoardTest() {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("add_new_board")));
        driver.findElement(By.id("add_new_board")).click();
        driver.findElement(By.id("board_name")).sendKeys("Board5");
        driver.findElement(By.id("board_name")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector("#crawler-sign-out > span")).click();
    }

    @Test
    public void createList() {
        driver.get("http://localhost:4000");
        driver.manage().window().setSize(new Dimension(760, 707));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("add_new_board")));
        driver.findElement(By.cssSelector("#\\37 2-abc > .inner")).click();
        driver.findElement(By.cssSelector(".add-new > .inner")).click();
        driver.findElement(By.id("list_name")).sendKeys("List2");
        driver.findElement(By.id("list_name")).sendKeys(Keys.ENTER);
    }

    @Test
    public void updateList() {
        driver.get("http://localhost:4000/");
        driver.manage().window().setSize(new Dimension(760, 707));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("add_new_board")));
        driver.findElement(By.cssSelector("#\\37 2-abc h4")).click();
        driver.findElement(By.cssSelector("#list_14 h4")).click();
        driver.findElement(By.id("list_name")).sendKeys("MyList");
        driver.findElement(By.cssSelector("button")).click();
    }

    @Test
    public void addCard() {
        driver.get("http://localhost:4000/");
        driver.manage().window().setSize(new Dimension(760, 707));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("add_new_board")));
        driver.findElement(By.cssSelector("#\\37 2-abc h4")).click();
        driver.findElement(By.linkText("Add a new card...")).click();
        driver.findElement(By.id("card_name")).sendKeys("This is card1");
        driver.findElement(By.cssSelector("button")).click();
    }

    @Test
    public void editCardDescription() {
        driver.get("http://localhost:4000/");
        driver.manage().window().setSize(new Dimension(760, 707));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("add_new_board")));
        driver.findElement(By.cssSelector("#\\37 2-abc h4")).click();
        driver.findElement(By.cssSelector("#card_13 span")).click();
        driver.findElement(By.linkText("Edit")).click();
        driver.findElement(By.cssSelector("textarea:nth-child(2)")).click();
        driver.findElement(By.cssSelector("textarea:nth-child(2)")).sendKeys("Description of card 1");
        driver.findElement(By.cssSelector("button:nth-child(3)")).click();
        driver.findElement(By.cssSelector(".fa-close")).click();
        driver.findElement(By.cssSelector(".view-container")).click();
    }

    @Test
    public void addCommentToCard() {
        driver.get("http://localhost:4000/");
        driver.manage().window().setSize(new Dimension(760, 707));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("add_new_board")));
        driver.findElement(By.cssSelector("#\\37 2-abc h4")).click();
        driver.findElement(By.cssSelector("#card_13 span")).click();
        driver.findElement(By.cssSelector("textarea")).click();
        driver.findElement(By.cssSelector("textarea")).sendKeys("First comment");
        driver.findElement(By.cssSelector("button")).click();
        driver.findElement(By.cssSelector(".fa-close")).click();
    }

    @Test
    public void addMemberToCard() {
        driver.get("http://localhost:4000/");
        driver.manage().window().setSize(new Dimension(760, 707));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("add_new_board")));
        driver.findElement(By.cssSelector("#\\37 2-abc > .inner")).click();
        driver.findElement(By.cssSelector("#card_13 footer")).click();
        driver.findElement(By.cssSelector(".button:nth-child(2) > span")).click();
        driver.findElement(By.cssSelector(".members-selector")).click();
        driver.findElement(By.cssSelector("ul:nth-child(2) span:nth-child(2)")).click();
    }

    @Test
    public void addAndRemoveTagToCard() {
        driver.get("http://localhost:4000/");
        driver.manage().window().setSize(new Dimension(760, 707));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("add_new_board")));
        driver.findElement(By.cssSelector("#\\37 2-abc > .inner")).click();
        driver.findElement(By.cssSelector("#card_13 > .card-content")).click();
        driver.findElement(By.linkText("Tags")).click();
        driver.findElement(By.cssSelector(".purple")).click();
        driver.findElement(By.cssSelector("li > .blue")).click();
        driver.findElement(By.linkText("Tags")).click();
        driver.findElement(By.cssSelector(".selected")).click();
        driver.findElement(By.cssSelector(".fa-close")).click();
    }

    @Test
    public void removeMemberFromCard() {
        driver.get("http://localhost:4000/");
        driver.manage().window().setSize(new Dimension(760, 707));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("add_new_board")));
        driver.findElement(By.cssSelector("#\\37 2-abc > .inner")).click();
        driver.findElement(By.cssSelector("#card_13 > .card-content")).click();
        driver.findElement(By.cssSelector(".button:nth-child(2) > span")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".button:nth-child(2) > span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector("ul:nth-child(2) span:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".md-content")).click();
        driver.findElement(By.cssSelector(".button:nth-child(2) > span")).click();
        driver.findElement(By.cssSelector("ul:nth-child(2) > li > a")).click();
        driver.findElement(By.cssSelector(".fa-close")).click();
    }

    @Test
    public void deleteCard() {
        driver.get("http://localhost:4000/");
        driver.manage().window().setSize(new Dimension(760, 707));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("add_new_board")));
        driver.findElement(By.cssSelector("#\\37 2-abc h4")).click();
        driver.findElement(By.cssSelector("#card_15 span")).click();
        driver.findElement(By.cssSelector(".fa-trash-o")).click();
    }

    @Test
    public void addNewMember() {
        driver.get("http://localhost:4000/");
        driver.manage().window().setSize(new Dimension(1550, 830));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("add_new_board")));
        driver.findElement(By.cssSelector("#\\37 2-abc > .inner")).click();
        driver.findElement(By.cssSelector(".fa-plus")).click();
        driver.findElement(By.id("crawljax_member_email")).click();
        driver.findElement(By.id("crawljax_member_email")).sendKeys("bsse1441@iit.du.ac.bd");
        driver.findElement(By.cssSelector("button")).click();
    }

    @Test
    public void signOut() {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(760, 707));
        driver.findElement(By.cssSelector("button")).click();
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#crawler-sign-out > span")));
        }
        driver.findElement(By.cssSelector("#crawler-sign-out > span")).click();
    }

    @Test
    public void viewAllBoard() {
        driver.get("http://localhost:4000/boards/72-abc");
        driver.manage().window().setSize(new Dimension(760, 707));
        driver.findElement(By.cssSelector("button")).click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#boards_nav span")));
        driver.findElement(By.cssSelector("#boards_nav span")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("#boards_nav span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.linkText("View all boards")).click();
    }
}
